//include files for the code

#include <stdio.h>
#include <fstream>
#include <sstream>
#include <chrono>
#include <opencv2/opencv.hpp>

//include the header file that was generated by ELL when compiling the model.
#include "model.h" 

// include the helper functions that were copied over earlier.
#include "tutorialHelpers.h"

//Define the following functions, which will help you get images from the camera and read in the categories file.
//when developing this code we will use picamera header and cpp files instead of this block 

// Read an image from the camera
static cv::Mat GetImageFromCamera(cv::VideoCapture& camera)
{
    cv::Mat frame;
    camera >> frame;
    return frame;
}

// Read a file of strings
static std::vector<std::string> ReadLinesFromFile(const std::string& filename)
{
    std::vector<std::string> lines;
    std::string line;

    std::ifstream file(filename);

    while (std::getline(file, line))
    {
        if (line.length() > 0) lines.emplace_back(line);
    }

    return lines;
}

//Define the main function, create a model wrapper object, and start the camera.
int main(int argc, char** argv)
{
    ModelWrapper wrapper;

  //The argument 0 in the function call above selects the default camera.
    cv::VideoCapture camera(0);
  
  //read the category names from the categories.txt file.
  //could this section be coded on another file?
   auto categories = ReadLinesFromFile("categories.txt");
  
  //The model expects its input in a certain shape. Get this shape and store it for use later on.
  TensorShape inputShape = wrapper.GetInputShape();
  
  
  //Models may need specific preprocessing for particular datasets, get the preprocessing tag for the model for use later on.
  tutorialHelpers::ImagePreprocessingMetadata metadata = tutorialHelpers::GetImagePreprocessingMetadata(wrapper);
  
  //Allocate a vector to store the model’s output.
   std::vector<float> predictions(wrapper.GetOutputSize());
  
  //Next, set up a loop that keeps going until the user presses the ESC key. At the start of each loop iteration, read an image from the camera, as follows.
  //I believe this would be the class 'stoprecording in camera'
   while ((cv::waitKey(1) & 0xFF) != 27)
    {
        cv::Mat image = GetImageFromCamera(camera);
     //The image stored in the image variable cannot be sent to the model as-is, because the model takes its input as a vector of float values. 
     //the model expects the input image to have a certain shape and a specific ordering of the color channels (in this case, Blue-Green-Red). Because preparing images for the model is a common operation, there is a helper function for it named PrepareImageForModel.
     
    auto input = tutorialHelpers::PrepareImageForModel(image, inputShape.columns, inputShape.rows, &metadata);
     
     //With the processed image input handy, call the Predict method to invoke the model.
        predictions = wrapper.Predict(input);
     
     //The predict method fills the predictions vector with the model output. 
     //Each element of this array corresponds to one of the 1,000 image classes recognized by the model. 
     //Extract the top five predicted categories by calling the helper function GetTopN.
     
      auto top5 = tutorialHelpers::GetTopN(predictions, 5);
    
     //Match the category indices in top5 with the category names in the categories file.
      std::stringstream headerText;
        for (auto element : top5)
        {
            headerText << categories[element.first] << " (" << std::floor(element.second * 100.0) << "%) ";
        }
     
     //Use the DrawHeader helper function to add the predicted category information to the top of the image. 
     //Then, display the resulting image on screen using the cv::imshow function.
            tutorialHelpers::DrawHeader(image, headerText.str());
        cv::imshow("ELL model", image);
    }
    return 0;
}
    
     
     
     
     
     
     
     
  
  
  
  
